name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.102
    - name: Install dependencies
      run: dotnet restore src/BusTimetable/BusTimetable.csproj
    - name: Build
      run: dotnet build src/BusTimetable/BusTimetable.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/BusTimetable.Tests/BusTimetable.Tests.csproj --no-restore --verbosity normal
